Repository astarte-platform/astartectl, pull requests merged in 2020-02, with the labels that each got.

#66 Enhance and Document utils gen-jwt
  CHANGELOG.md
  cmd/appengine/appengine.go
  cmd/housekeeping/housekeeping.go
  cmd/pairing/pairing.go
  cmd/realm/realm.go
  cmd/utils/utils.go
  utils/token.go
Labels: documentation, enhancement, user experience

#68 Prepare 0.10.6
  CHANGELOG.md
  cmd/version.go
Labels: chore

#69 Add database retention policy and ttl mapping attributes
  common/astarte_interface.go
Labels: chore

#63 README.md: Add a tip regarding $PATH
  README.md
Labels: documentation

#71 Prepare 0.11.0 rc.0
  CHANGELOG.md
  cmd/version.go
Labels: chore
