Repository astarte-platform/astartectl, pull requests merged in 2020-10, with the labels that each got.

#111 Update astarte-go, adding support for EC keys
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  go.mod
  go.sum
Labels: enhancement

#112 Add support for EC keys in housekeeping realm generation
  cmd/housekeeping/realms.go
  go.mod
Labels: enhancement, user experience

#113 Prepare v0.11.2 release
  CHANGELOG.md
  cmd/version.go
Labels: chore
