Repository astarte-platform/astartectl, pull requests merged in 2023-07, with the labels that each got.

#213 Fix appengine send-data for binaryblob
  CHANGELOG.md
  cmd/appengine/device.go
  go.mod
  go.sum
Labels: bug, minor

#215 `cluster instance deploy`: allow to deploy Astarte >= v1.1.0
  CHANGELOG.md
  cmd/cluster/deployment/all_profiles.go
  cmd/cluster/deployment/basic_1.1.go
  cmd/cluster/deployment/burst_1.1.go
Labels: chore, user experience

#216 Bump astarte-go to v0.91.1
  CHANGELOG.md
  cmd/realm/interfaces.go
  go.mod
  go.sum
Labels: chore

#217 Prepare 22.11.03
  CHANGELOG.md
  cmd/version.go
Labels: chore

#218 Workflows: update release CI
  .github/workflows/goreleaser.yml
  .goreleaser.yml
Labels: minor
