Repository astarte-platform/astartectl, pull requests merged in 2023-03, with the labels that each got.

#171 `cluster instance deploy`: use v1alpha2 API for Astarte >= 1.0
  CHANGELOG.md
  cmd/cluster/cluster.go
  cmd/cluster/deployment/astarte_cluster_profile.go
  cmd/cluster/deployment/astarte_deployment.go
  cmd/cluster/deployment/basic_0.10.go
  cmd/cluster/deployment/basic_0.11.go
  cmd/cluster/deployment/basic_1.0.go
  cmd/cluster/deployment/burst_0.11.go
  cmd/cluster/deployment/burst_1.0.go
  cmd/cluster/instance_deploy.go
  cmd/cluster/profile_helpers.go
Labels: minor, user experience

#172 Internals: move to the latest `astarte-go`
  .github/workflows/goreleaser.yml
  .github/workflows/main.yml
  .tool-versions
  CHANGELOG.md
  cmd/appengine/appengine.go
  cmd/appengine/device.go
  cmd/appengine/device_aliases.go
  cmd/appengine/device_attributes.go
  cmd/appengine/device_credentials.go
  cmd/appengine/groups.go
  cmd/appengine/stats.go
  cmd/housekeeping/housekeeping.go
  cmd/housekeeping/realms.go
  cmd/pairing/agent.go
  cmd/pairing/pairing.go
  cmd/realm/interfaces.go
  cmd/realm/realm.go
  cmd/realm/triggers.go
  cmd/utils/device_id.go
  cmd/utils/interfaces.go
  cmd/utils/utils.go
  go.mod
  go.sum
  utils/client.go
Labels: chore

#184 `appengine:` check if RM URL is set when auxiliary queries may be used
  cmd/appengine/device.go
  go.mod
  go.sum
  utils/client.go
Labels: minor

#185 Bump dependencies
  go.mod
  go.sum
Labels: chore

#186 Prepare 22.11.01 release
  CHANGELOG.md
  README.md
  cmd/version.go
Labels: chore

#187 Forward port changes from release-22.11
  .github/workflows/goreleaser.yml
  .github/workflows/main.yml
  .tool-versions
  CHANGELOG.md
  README.md
  cmd/appengine/appengine.go
  cmd/appengine/device.go
  cmd/appengine/device_aliases.go
  cmd/appengine/device_attributes.go
  cmd/appengine/device_credentials.go
  cmd/appengine/groups.go
  cmd/appengine/stats.go
  cmd/cluster/cluster.go
  cmd/cluster/deployment/astarte_cluster_profile.go
  cmd/cluster/deployment/astarte_deployment.go
  cmd/cluster/deployment/basic_0.10.go
  cmd/cluster/deployment/basic_0.11.go
  cmd/cluster/deployment/basic_1.0.go
  cmd/cluster/deployment/burst_0.11.go
  cmd/cluster/deployment/burst_1.0.go
  cmd/cluster/instance_deploy.go
  cmd/cluster/profile_helpers.go
  cmd/housekeeping/housekeeping.go
  cmd/housekeeping/realms.go
  cmd/pairing/agent.go
  cmd/pairing/pairing.go
  cmd/realm/interfaces.go
  cmd/realm/realm.go
  cmd/realm/triggers.go
  cmd/root.go
  cmd/utils/device_id.go
  cmd/utils/interfaces.go
  cmd/utils/utils.go
  cmd/version.go
  go.mod
  go.sum
  utils/client.go
  utils/cmdline.go
Labels: chore
