Repository astarte-platform/astartectl, pull requests merged in 2023-06, with the labels that each got.

#204 `send-data`: fix curl representation
  CHANGELOG.md
  cmd/appengine/device.go
Labels: documentation, minor

#208 Bump github workflows dependencies
  .github/workflows/goreleaser.yml
  .github/workflows/main.yml
Labels: chore

#209 Add `realm-management interfaces save` command
  CHANGELOG.md
  cmd/realm/interfaces.go
Labels: enhancement, user experience

#212 Build workflow: save build artifacts
  .github/workflows/main.yml
Labels: user experience
