Repository astarte-platform/astartectl, pull requests merged in 2023-05, with the labels that each got.

#191 Context: Stop warning about missing configuration, again
  CHANGELOG.md
  cmd/root.go
Labels: minor

#193 Fix appengine devices list
  cmd/appengine/device.go
Labels: bug

#196 Fix get-samples and data-snapshot
  CHANGELOG.md
  cmd/appengine/device.go
  go.mod
  go.sum
Labels: bug, user experience

#197 Prepare release 22.11.02
  CHANGELOG.md
  cmd/version.go
Labels: chore

#198 Forward port changes from release-22.11
  CHANGELOG.md
  cmd/appengine/device.go
  cmd/root.go
  cmd/version.go
  go.mod
  go.sum
Labels: chore

#201 Install and update interfaces are now synchronous.
  CHANGELOG.md
  cmd/realm/interfaces.go
  go.mod
  go.sum
Labels: enhancement, minor, user experience
