Repository astarte-platform/astartectl, pull requests merged in 2024-09, with the labels that each got.

#253 Prepare 23.5.2 release
  CHANGELOG.md
  cmd/version.go
Labels: chore

#254 Goreleaser: add version number to config file
  .goreleaser.yml
Labels: chore

#264 `cluster instance`: deprecate `destroy`, `install` and `show` commands
  CHANGELOG.md
  cmd/cluster/instance_deploy.go
  cmd/cluster/instance_destroy.go
  cmd/cluster/instance_show.go
Labels: minor, user experience

#270 Prepare 24.5.2 release
  CHANGELOG.md
  cmd/version.go
Labels: chore

#271 Prepare next development cycle, i.e.: 24.11
  CHANGELOG.md
  cmd/version.go
Labels: chore

#272 Add trigger delivery policy basic operations
  cmd/realm/trigger_policies.go
Labels: enhancement, user experience
